apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpletimeservice-sa
  namespace: simpletimeservice
  labels:
    app.kubernetes.io/name: simpletimeservice
    app.kubernetes.io/part-of: particle41-devops-challenge
